### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Rafnuss** [Zoziologie/GlobalRareeBird#1]
- [ ] Popup: link to google map
- [ ] Popup: larger link icon
- [ ] Loading message: several line
- [ ] Select country: subregion for US and Canada as sub-selection 
- [ ] countrie added, delete per country, label or tag style, generate link below, write into coockie otherwise ?
- [ ] filter very slow
- [ ] update text date on the filter
- [ ] debug no obs in country

**Comment by Rafnuss** [comment]
No direct link to picture available: https://documenter.getpostman.com/view/664302/S1ENwy59
Best would be to add a link to checklist with `?view=photos` but too many link then.

**Comment by Rafnuss** [comment]
try to use iframe but seems quit complicated as it could not load external js script
